version: '3.8'

services:
  coze-discord-bridge:
    build: .
    container_name: coze-discord-bridge
    environment:
      - token=xxxxxxxxxxxx
      - discord_server=xxxxxxxxxxxx
      - coze_bot=xxxxxxxxxxxx
      - key=default
    ports:
      - "8092:8092"
      - "8093:8093"
    volumes:
      - coze-discord-bridge:/data
    restart: unless-stopped
volumes:
  coze-discord-bridge:
    driver: local